<!DOCTYPE html>
<!--[if lt IE 7]>		<html class="no-js lt-ie10 lt-ie9 lt-ie8 lt-ie7" lang="en" > <![endif]-->
<!--[if IE 7]>			<html class="no-js lt-ie10 lt-ie9 lt-ie8 gt-ie6" lang="en" > <![endif]-->
<!--[if IE 8]>			<html class="no-js lt-ie10 lt-ie9 gt-ie7 gt-ie6 lang="en" > <![endif]-->
<!--[if IE 9]>			<html class="no-js lt-ie10 gt-ie8 gt-ie7 gt-ie6 lang="en" > <![endif]-->
<!--[if gt IE 9]>	<html class="no-js gt-ie9 gt-ie8 gt-ie7 gt-ie6" lang="en"> <![endif]-->
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<title>CUBE SUMATION</title>
	<meta name="viewport" content="initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no, width=device-width">
	<meta name="format-detection" content="telephone=no">
	<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
	<link rel="icon" href="/favicon.ico" type="image/x-icon">
</head>
<body>
	<header>
	</header>
	<section id="page">
		<?=$this->yield;?>
	</section>
	<footer>
	</footer>
</body>
</html>